### ISSUE TITLE
Oracle search lists the same table

### ISSUE THREAD

**Issue by DominicEliot** [XenotropicDev/TheOracle2#10]
![image](https://user-images.githubusercontent.com/6792312/148405673-86572469-b77c-4010-b812-84478105d845.png)

This is caused by the subcategories in the Dataforged data. More detailed entries and a better db search query should fix this.

**Comment by rsek** [comment]
yeah, this is one reason i think it'd be good to default to an oracle's path/string id for most/all user-facing oracle labels that otherwise lack context to make their category clear (another big one is being able to parse them consistently from embed fields).

i've got both a keyed version (read: dictionary-ready) and a structured version (read: closer to the current structure) of the data in this branch, plus corresponding classes in the DataClassesNext folder. i haven't tried to put them in the DB yet, but the appear to at least deserialize properly into the classes.

the keyed version (`oracle_paths.json`) is keyed with the path strings, while the structured version (`oracles_next.json`) includes a `_path` key associated with every category and oracle.

https://github.com/rsek/TheOracle2/tree/oracle-paths

**Comment by rsek** [comment]
oh, and i'm not totally sure from your post, but figure it bears saying in case you missed it: those probably aren't the same table, technically speaking. they're just multiple tables with the same `Name` field. generally names are only unique within a given category. this is done to both reflect the "data structure" of the book itself, and to make it easy to recognize/search for tables that have similar use cases (and tend to bear standardized names like "Peril", "Feature", "Opportunity", etc).

one practical application of this would be constructing oracle arrays (p. 378) of multiple peril tables... or just searching `peril` to get a list of all peril tables to choose from.

**Comment by rsek** [comment]
hah, forgot the actual point i had: maybe we solve this by switching to the new dataforged format? i'm fairly satisfied with its general structure - any future changes will probably be to keys devoted to object/oracle references or grammatical data... and revising those is probably best done after seeing how well they work in a practical case like TheOracle anyways.

(apologies for the spam, the second and third posts seemed too big to make sense as edits, ha)

**Comment by DominicEliot** [comment]
> oh, and i'm not totally sure from your post, but figure it bears saying in case you missed it: those probably aren't the same table, technically speaking. they're just multiple tables with the same `Name` field. 

Yeah, I got that, I was just making a quick note of the issue here so that it didn't get forgotten for longer than it should :-)

> hah, forgot the actual point i had: maybe we solve this by switching to the new dataforged format? i'm fairly satisfied with its general structure - any future changes will probably be to keys devoted to object/oracle references or grammatical data... and revising those is probably best done after seeing how well they work in a practical case like TheOracle anyways.

I'm up for that too if you think it's in a state where doing a try implementation will be helpful. But as a quick fix I think I'm going to add some details to the search output.

**Comment by rsek** [comment]
> Yeah, I got that, I was just making a quick note of the issue here so that it didn't get forgotten for longer than it should :-)

cool, figured i should make sure just in case - i imagine it would suck to troubleshoot with missing information because i made some less-than-obvious, currently-poorly-documented choices with dataforged, ha.

> I'm up for that too if you think it's in a state where doing a try implementation will be helpful.

it'd be helpful in refining dataforged's new format at least ;) wouldn't be surprised to encounter some weirdness in implementing it in TheOracle2, but in my view that's the best way of working the kinks out, and in making the data more useful for TheOracle in the long run.

**Comment by DominicEliot** [comment]
I added a little bit of code to make the search results better. I'm going to close this issue and open a new issue/PR for the new dataforged format. If we need to open this back up or a new issue once everything is ported over that can be done.
