### ISSUE TITLE
Components cannot change without generating a new discord message

### ISSUE THREAD

**Issue by DominicEliot** [XenotropicDev/TheOracle2#18]
Currently if things change within a components ID all the bot users will need to remake their character to solve the issue.

My initial thought is that any breaking component ID changes should keep the old ID signature around for a while and convert the message to the new format if possible, or alert the user if not.

I'm not sure if there's some kind of framework that can be developed to help with this issue, but I wanted to post this as an issue so that others can discuss it, and I can have a place for any ideas I have regarding this topic.

For the time being this isn't a huge issue as the bot is still in an alpha phase, but as we get closer, and up to a release it will become a big issue as the bot user base grows.

**Comment by rsek** [comment]
here's one way i've handled it in XenotropicDev/TheOracle2#29:

<img width="562" alt="Screen Shot 2022-01-24 at 4 14 22 PM" src="https://user-images.githubusercontent.com/5354757/150886609-72df4f49-8115-4cb9-a711-a99f322cf8ba.png">

but that only really works if they're using the same parameters. i've brought it up before, but including it here for the sake of completeness: i think it'd be a good to move everything from `action-name-param1-param2` to `action-name:param1,param2` so that the delimiting characters are well-distinguished (see XenotropicDev/TheOracle#70)

some other ideas:
- a component to refresh/rebuild an entity embed from the DB? might not be a bad idea on the character sheet anyways, so ppl can update it without incrementing/decrementing the sheet
- including fallback options so customid interactions can collapse more gracefully if they're missing certain information. for example: if the customid for an action roll related custom id is missing info or is otherwise malformed, ephemeral prompts ask the user to set the Player Character, Stat, and Adds manually from a dropdown selection, then executes the command with that info
  - these sorts of prompts could be standardized for use throughout the bot via a class/interface
  - having a *series* of ephemeral prompts to get several parameters might be possible if we work out some means of passing the data forward to the next prompt (in the custom ID, or in an embed conveying "here's the choices you've made so far", or simply as part of message text
- another possibility (not necessarily mutually exclusive) would be falling back to embed parsing. that's not ideal, obv, but as a backup it could be handy.
  - it'd also only have to happen once
  - this is a long shot, but: is there a practical, programmatic way to reverse a function that transforms a value into an output string, step-by-step? or to write them in such a way that this is possible? writing a bunch of regexes isn't the end of the world,, but having it be something where the compatibility is maintained automatically would be nice.
  - FWIW, i've been trying to encapsulate embed info in individual fields (for Challenge Dice, etc) in a standardized way (e.g. all things that use challenge dice a field with the same format) so that getting the data back out is a bit more reliable. it's still a work in progress tho.
- gonzo option: what if the primary means of viewing the character entity was **just** ephemerals? like, no particular assumption of the presence of a permanent embed, it's just something where you do `/sheet` to bring up an ephemeral with the character embed to view whenever you need it, and dismiss when you're done with it. then we don't have to worry much about maintaining component compatibility, or the display being out-of-sync with the DB entity's current state - people will pretty much always be interacting with the most up-to-date version
  - possible downsides: too disconnected/abstracted from "embed = character sheet" metaphor? no semi-permanent artifact of PC for display in a channel? 🤔 
  - tbh, this command might not be a bad idea to have anyways, just so ppl can quickly glance at their sheet without looking at a different channel... which might be a good avenue to gather feedback on whether it being the primary means of accessing a PC would work for ppl.
    - long term, we might even be able to stick it in a modal or something, but that's a ways off.
